version: "3"

volumes: 
  db-data:
  pgadmin4-var-lib-postgres:

networks:
  database:
    driver: bridge
  esqlate:
    driver: bridge

services:

  db:
    image: postgres:12
    environment:
    - POSTGRES_PASSWORD=postgres
    # ports:
    # - "127.0.0.1:5432:5432"
    volumes:
    - db-data:/var/lib/postgresql/data
    networks:
    - database

  db_loader:
    build:
      context: ./node_modules/esqlate-server
      dockerfile: Dockerfile-load-northwind-example-database
    environment:
    - PGUSER=postgres
    - PGPASSWORD=postgres
    - PGDATABASE=postgres
    - PGHOST=db
    networks:
    - database

  server:
    build:
      context: ./node_modules/esqlate-server
      dockerfile: Dockerfile
    environment:
    # - DEFINITION_DIRECTORY=definition
    - LISTEN_PORT=80
    - PGUSER=postgres
    - PGPASSWORD=postgres
    - PGDATABASE=postgres
    - PGHOST=db
    volumes:
    # - ./esqlate-server/example_definition:/esqlate-server/definition:ro # To use this uncomment the DEFINITION_DIRECTORY comment without environment
    - ./persistence:/node_modules/esqlate-server/persistence
    networks:
    - database
    - esqlate

  reaper:
    build:
      context: ./node_modules/esqlate-server
      dockerfile: Dockerfile-reaper
    environment:
    - AGE_BEFORE_CLEANING=1
    - LOCATION=./persistence
    volumes:
    - ./persistence:/node_modules/esqlate-server/persistence

  front:
    build:
      context: ./node_modules/esqlate-front
      dockerfile: Dockerfile
    environment:
    - API_SERVER=/esqlate-server/
    - LISTEN_PORT=80
    - HOST=0.0.0.0 # Make sirv listen on all IPs for NGINX
    networks:
    - esqlate

  nginx:
    image: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - "127.0.0.1:8800:80"
    networks:
    - esqlate
